### ISSUE TITLE
ER: Don't strip EOF on Vue files, allow possibility to have a new line at EOF

### ISSUE THREAD

**Issue by voool** [malobre/dprint-plugin-vue#5]
It looks like with v0.3.2, the end of the .Vue file is always trimmed, 

~and therefore even though my dprint.json config looks like~

~{~
~"newLineKind": "lf",~
 ~....~
  ~"vue"~
   ~....~
~}~

~When I run dprint on a Vue file, the end of the line is always stripped.~

~I can get a reproducer up for this.~

**Update**: `newLineKind` is specific to the typescript/javascript plugin https://dprint.dev/plugins/typescript/config/ so it only makes sense that the config isn't used by this plugin.  I am re-naming this issue to be an ER to enable adding a newline / keeping the existing newline to EOF.

**Comment by malobre** [comment]
`newLineKind` is neither a global option nor a `dprint-plugin-vue` option.

To clarify, you want the option to have a new line at EOF ?

**Comment by voool** [comment]
Ah my mistake, newLineKind is specific to the typescript/javascript plugin https://dprint.dev/plugins/typescript/config/

> To clarify, you want the possibility to have a new line at EOF ?

Correct

**Comment by malobre** [comment]
Plugin behaviour was changed in latest version (0.5.0), a newline is now printed at EOF.
