### ISSUE TITLE
Plugin is broken?

### ISSUE THREAD

**Issue by xxshady** [malobre/dprint-plugin-vue#6]
When i run `dprint fmt` nothing happens

`dprint.json`
```json
{
  "includes": [
    "webview/src/**/*.vue"
  ],
  "plugins": [
    "https://plugins.dprint.dev/malobre/vue-v0.5.0.wasm"
  ]
}
```

`dprint fmt --verbose` output:
```
PS project> dprint fmt --verbose
[VERBOSE] Creating directory: C:\Users\user\AppData\Local\dprint\cache
[VERBOSE] Reading file: C:\Users\user\AppData\Local\dprint\cache\cache-manifest.json
[VERBOSE] Reading file: C:\Users\user\AppData\Local\dprint\cache\plugin-cache-manifest.json
[VERBOSE] Checking path exists: project\dprint.json
[VERBOSE] Reading file: project\dprint.json
[VERBOSE] Reading file: C:\Users\user\AppData\Local\dprint\cache\plugins\dprint-plugin-vue\0.5.0-x86_64.cached
[VERBOSE] Globbing: GlobPatterns { includes: [GlobPattern { relative_pattern: "webview/src/**/*.vue", base_dir: CanonicalizedPathBuf { path: "project" } }], excludes: [GlobPattern { relative_pattern: "!**/node_modules", base_dir: CanonicalizedPathBuf { path: "project" } }] }
[VERBOSE] File(s) matched: ["project\\webview\\src\\App.vue", "project\\webview\\src\\components\\HelloWorld.vue"]
[VERBOSE] Finished globbing in 10ms
[VERBOSE] Reading file: C:\Users\user\AppData\Local\dprint\cache\project.incremental
[VERBOSE] Max threads: 12
Thread count: 11
[VERBOSE] Creating instance of dprint-plugin-vue
[VERBOSE] Created instance of dprint-plugin-vue in 0ms
[VERBOSE] Reading file: project\webview\src\components\HelloWorld.vue
[VERBOSE] Reading file: project\webview\src\App.vue
[VERBOSE] No change: project\webview\src\components\HelloWorld.vue
[VERBOSE] No change: project\webview\src\App.vue
[VERBOSE] Writing file: C:\Users\user\AppData\Local\dprint\cache\project.incremental
PS project> 
```

`webview/src/App.vue`
```vue
<script setup lang="ts">
              let a = 'awdwd'    ;
              
              
              
              
              let b={a:10}
</script>

<template>
  {{ 10 }}
</template>
```

**Comment by voool** [comment]
The plugin is formatting Vue files correctly for me. This is my `dprint.json`

> {
  "newLineKind": "lf",
  "typescript": {
    "quoteStyle": "preferSingle",
    "spaceSurroundingProperties": false,
    "objectExpression.spaceSurroundingProperties": false,
    "objectPattern.spaceSurroundingProperties": false,
    "typeLiteral.spaceSurroundingProperties": false,
    "exportDeclaration.spaceSurroundingNamedExports": false,
    "importDeclaration.spaceSurroundingNamedImports": false,
    "exportDeclaration.sortNamedExports": "maintain",
    "importDeclaration.sortNamedImports": "maintain",
    "module.sortImportDeclarations": "maintain",
    "functionExpression.spaceBeforeParentheses": true
  },
  "vue": {
    "indentTemplate": false
  },
  "includes": ["src/**/*.{ts,tsx,js,jsx,cjs,mjs,json,vue}"],
  "excludes": [
    "**/node_modules",
    "yarn.lock",
    "dist"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.74.0.wasm",
    "https://plugins.dprint.dev/json-0.15.6.wasm",
    "https://plugins.dprint.dev/disrupted/css-0.1.3.wasm",
    "https://plugins.dprint.dev/malobre/vue-v0.5.0.wasm"
  ]
}

You might not have the correct plugins installed. Try installing the typescript plugin

Taken from the README:
> Install plugins for the languages contained in your vue files.

**Comment by xxshady** [comment]
Oh, yeah, my problem was the lack of typescript plugin, thank you!
